name: 2job_workflow
on: 
  pull_request:
    branches:
     - main
  workflow_dispatch: 

# Testing our first workflow

jobs: 
  job1:
    runs-on: ubuntu-latest 
    steps:
        - name: step1
          run: echo "hello from step1, job1 of workflow1"
        - name: my step2
          run: echo "hello from dan"
        - run: echo "hello from step 3"
        - name: my step 4 for testing multiple lines of code execution
          run: | 
            ls -l
            pwd
            sudo cat /etc/os-release
            uname -a
            echo "final step4 execution done"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
     - run: echo "job2 run after job1 completed successfully"
    
