name: cicd
on: 
  push:
    branches:
      - main
  workflow_dispatch:
# Testing our first workflow
jobs:
  build-a: 
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "hello from step1"
          sleep 10
      - name: my step2
        run: |
          echo "$greetings from $name"
          sleep 10
          
  build-b: 
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "hello from step1"
          sleep 10
      - name: my step2
        run: |
          echo "$greetings from $name"
          sleep 10        
          
  test: 
     runs-on: ubuntu-latest
     needs: [ build-a, build-b ]
     if: ${{ always() }}
     steps:
      - name: step1
        run: |
          echo "hello from step1"
          sleep 10
      - name: my step2
        run: |
          echo "$greetings from $name"
          sleep 10
          echo "hello from step2"  
          sleep 10
          
  deploy: 
     runs-on: ubuntu-latest
     needs: test 
     steps:
      - name: step1
        run: |
          echo "hello from step1"
          sleep 10
      - name: my step2
        run: |
          echo "hello from step2"

  notification-start: 
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "Job started"
          sleep 10
          
  notification-failed: 
    runs-on: ubuntu-latest
    needs: build-a
    if: ${{ needs.build.result == 'failure' || failure() }}
    steps:
      - name: notify
        run: |
          echo "Job Failure"
          sleep 10
              
