name: continous-build
on: 
  push:  
    branches:
    - main
    - dev
  pull_request:
    branches:
     - main
  workflow_dispatch: 

# Testing our first workflow
env:
  name: Daniel
  
jobs: 
  build:
    runs-on: ubuntu-latest 
    env:
      environment: Dev
      lastname: Barger
    steps:
        - name: step1
          env:
            greetings: Good Morning
            name: Sandeep
          run: | 
           echo "$greetings from $name $lastname, job1 of workflow1 in environment $environment"
           sleep 30
           hostname
        - name: my step2
          run: |
            echo "hello from $name"
            sleep 10
        - run: |
            echo "hello from step 3"
            sleep 10
        - name: my step 4 for testing multiple lines of code execution
          run: | 
            ls -l
            pwd
            sudo cat /etc/os-release
            uname -a
            echo "final step4 execution done"
  test:
    runs-on: self-hosted
    env:
      environment: staging
    steps:
        - name: step1
          run: |
            echo "$greetings from $name $lastname, job1 of workflow1 in environment $environment"
            sleep 30
            hostname
        - name: my step2
          run: |
            echo "hello from dan"
            sleep 10
        
